# Generated by Django 5.1 on 2024-08-26 08:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('no_of_guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('date', models.DateField(choices=[(datetime.date(2024, 8, 26), datetime.date(2024, 8, 26)), (datetime.date(2024, 8, 27), datetime.date(2024, 8, 27)), (datetime.date(2024, 8, 28), datetime.date(2024, 8, 28)), (datetime.date(2024, 8, 29), datetime.date(2024, 8, 29)), (datetime.date(2024, 8, 30), datetime.date(2024, 8, 30)), (datetime.date(2024, 8, 31), datetime.date(2024, 8, 31)), (datetime.date(2024, 9, 1), datetime.date(2024, 9, 1))], db_index=True)),
                ('time', models.TimeField(choices=[(datetime.time(21, 0), '9 PM'), (datetime.time(21, 5), '9:05 PM'), (datetime.time(21, 10), '9:10 PM'), (datetime.time(21, 15), '9:15 PM'), (datetime.time(21, 20), '9:20 PM'), (datetime.time(21, 25), '9:25 PM'), (datetime.time(21, 30), '9:30 PM')], unique_for_date='date')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
