# Generated by Django 5.1 on 2024-08-26 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 8, 26), datetime.date(2024, 8, 26)), (datetime.date(2024, 8, 27), datetime.date(2024, 8, 27)), (datetime.date(2024, 8, 28), datetime.date(2024, 8, 28)), (datetime.date(2024, 8, 29), datetime.date(2024, 8, 29)), (datetime.date(2024, 8, 30), datetime.date(2024, 8, 30)), (datetime.date(2024, 8, 31), datetime.date(2024, 8, 31)), (datetime.date(2024, 9, 1), datetime.date(2024, 9, 1))], db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(choices=[('21:00:00', '9 PM'), ('21:05:00', '9:05 PM'), ('21:10:00', '9:10 PM'), ('21:15:00', '9:15 PM'), ('21:20:00', '9:20 PM'), ('21:25:00', '9:25 PM'), ('21:30:00', '9:30 PM'), ('21:35:00', '9:35 PM'), ('21:40:00', '9:40 PM'), ('21:45:00', '9:45 PM'), ('21:50:00', '9:50 PM'), ('21:55:00', '9:55 PM'), ('22:00:00', '10 PM'), ('22:05:00', '10:05 PM'), ('22:10:00', '10:10 PM'), ('22:15:00', '10:15 PM'), ('22:20:00', '10:20 PM'), ('22:25:00', '10:25 PM'), ('22:30:00', '10:30 PM'), ('22:35:00', '10:35 PM'), ('22:45:00', '10:45 PM'), ('22:50:00', '10:50 PM'), ('22:55:00', '10:55 PM'), ('23:00:00', '11 PM')], unique_for_date='date'),
        ),
    ]
