# Generated by Django 5.1 on 2024-08-26 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(choices=[(datetime.time(21, 0), '9 PM'), (datetime.time(21, 5), '9:05 PM'), (datetime.time(21, 10), '9:10 PM'), (datetime.time(21, 15), '9:15 PM'), (datetime.time(21, 20), '9:20 PM'), (datetime.time(21, 25), '9:25 PM'), (datetime.time(21, 30), '9:30 PM'), (datetime.time(21, 35), '9:35 PM'), (datetime.time(21, 40), '9:40 PM'), (datetime.time(21, 45), '9:45 PM'), (datetime.time(21, 50), '9:50 PM'), (datetime.time(21, 55), '9:55 PM'), (datetime.time(22, 0), '10 PM')], db_index=True, unique_for_date='date'),
        ),
    ]
